<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.298" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2025-10-04T22:25:03" tests="0" file="cypress/e2e/pet-details.navigation.cy.ts" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Pet Details – navigation smoke" timestamp="2025-10-04T22:25:03" tests="1" time="0.297" failures="1">
    <testcase name="Pet Details – navigation smoke opens the first pet from the list and lands on details page" time="0.000" classname="opens the first pet from the list and lands on details page">
      <failure message="cy.findByRole(...).then(...).catch is not a function" type="TypeError"><![CDATA[TypeError: cy.findByRole(...).then(...).catch is not a function
    at loginIfNeeded (webpack://frontend/./cypress/e2e/pet-details.navigation.cy.ts:13:10)
    at Context.eval (webpack://frontend/./cypress/e2e/pet-details.navigation.cy.ts:24:4)
    at runnable.fn (http://localhost:5173/__cypress/runner/cypress_runner.js:141863:19)
    at callFn (http://localhost:5173/__cypress/runner/cypress_runner.js:160932:21)
    at Runnable.run (http://localhost:5173/__cypress/runner/cypress_runner.js:160919:7)
    at <unknown> (http://localhost:5173/__cypress/runner/cypress_runner.js:167014:30)
    at PassThroughHandlerContext.finallyHandler (http://localhost:5173/__cypress/runner/cypress_runner.js:4042:23)
    at PassThroughHandlerContext.tryCatcher (http://localhost:5173/__cypress/runner/cypress_runner.js:1777:23)
    at Promise._settlePromiseFromHandler (http://localhost:5173/__cypress/runner/cypress_runner.js:1489:31)]]></failure>
    </testcase>
  </testsuite>
</testsuites>