<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.143" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2025-10-05T00:20:55" tests="1" file="cypress/e2e/owner-details.navigation.cy.ts" time="0.141" failures="1">
    <testcase name="An uncaught error was detected outside of a test" time="0.000" classname="An uncaught error was detected outside of a test">
      <failure message="The following error originated from your test code, not from Cypress.

  &gt; `Cypress.Commands.addQuery()` is used to create new queries, but `findAllByLabelText` is an existing Cypress command or query, or is reserved internally by Cypress.

 If you want to override an existing command or query, use `Cypress.Commands.overrideQuery()` instead.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

https://on.cypress.io/api/custom-queries" type="CypressError"><![CDATA[CypressError: The following error originated from your test code, not from Cypress.

  > `Cypress.Commands.addQuery()` is used to create new queries, but `findAllByLabelText` is an existing Cypress command or query, or is reserved internally by Cypress.

 If you want to override an existing command or query, use `Cypress.Commands.overrideQuery()` instead.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

https://on.cypress.io/api/custom-queries
    at internalError (http://localhost:5173/__cypress/runner/cypress_runner.js:113261:39)
    at Object.addQuery (http://localhost:5173/__cypress/runner/cypress_runner.js:113382:11)
    at eval (webpack://frontend/./node_modules/@testing-library/cypress/dist/add-commands.js:8:0)
    at Array.forEach (<anonymous>)
    at ./node_modules/@testing-library/cypress/dist/add-commands.js (webpack://frontend/./node_modules/@testing-library/cypress/dist/add-commands.js:4:0)
    at __webpack_require__ (webpack://frontend/webpack/bootstrap:19:0)
    at ./node_modules/@testing-library/cypress/add-commands.js (webpack://frontend/./node_modules/@testing-library/cypress/add-commands.js:4:0)
    at __webpack_require__ (webpack://frontend/webpack/bootstrap:19:0)
    at eval (webpack://frontend/./cypress/e2e/owner-details.navigation.cy.ts:3:0)
    at eval (http://localhost:5173/__cypress/tests?p=cypress/e2e/owner-details.navigation.cy.ts:15060:3)

From Cypress Internals:
      at internalError (http://localhost:5173/__cypress/runner/cypress_runner.js:113265:91)
      at Object.addQuery (http://localhost:5173/__cypress/runner/cypress_runner.js:113382:11)
      at eval (webpack://frontend/./node_modules/@testing-library/cypress/dist/add-commands.js:8:0)
  at Array.forEach (<anonymous>)
      at ./node_modules/@testing-library/cypress/dist/add-commands.js (webpack://frontend/./node_modules/@testing-library/cypress/dist/add-commands.js:4:0)
      at __webpack_require__ (webpack://frontend/webpack/bootstrap:19:0)
      at ./node_modules/@testing-library/cypress/add-commands.js (webpack://frontend/./node_modules/@testing-library/cypress/add-commands.js:4:0)
      at __webpack_require__ (webpack://frontend/webpack/bootstrap:19:0)
      at eval (webpack://frontend/./cypress/e2e/owner-details.navigation.cy.ts:3:0)
      at eval (http://localhost:5173/__cypress/tests?p=cypress/e2e/owner-details.navigation.cy.ts:15060:3)
      at eval (http://localhost:5173/__cypress/tests?p=cypress/e2e/owner-details.navigation.cy.ts:15062:12)
  at eval (<anonymous>)
      at <unknown> (http://localhost:5173/__cypress/runner/cypress_runner.js:113149:23)
      at tryCatcher (http://localhost:5173/__cypress/runner/cypress_runner.js:1777:23)
      at Object.gotValue (http://localhost:5173/__cypress/runner/cypress_runner.js:6446:18)
      at Object.gotAccum (http://localhost:5173/__cypress/runner/cypress_runner.js:6435:25)
      at Object.tryCatcher (http://localhost:5173/__cypress/runner/cypress_runner.js:1777:23)
      at Promise._settlePromiseFromHandler (http://localhost:5173/__cypress/runner/cypress_runner.js:1489:31)
      at Promise._settlePromise (http://localhost:5173/__cypress/runner/cypress_runner.js:1546:18)
      at Promise._settlePromise0 (http://localhost:5173/__cypress/runner/cypress_runner.js:1591:10)
      at Promise._settlePromises (http://localhost:5173/__cypress/runner/cypress_runner.js:1671:18)
      at _drainQueueStep (http://localhost:5173/__cypress/runner/cypress_runner.js:2377:12)]]></failure>
    </testcase>
  </testsuite>
</testsuites>