<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="9.456" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2025-10-05T17:12:38" tests="0" file="cypress/e2e/appointments.navigation.cy.ts" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Appointments – list visibility" timestamp="2025-10-05T17:12:38" tests="1" time="9.449" failures="1">
    <testcase name="Appointments – list visibility navigates to Appointments via sidebar and (optionally) opens first item" time="0.000" classname="navigates to Appointments via sidebar and (optionally) opens first item">
      <failure message="Timed out retrying after 4000ms: Expected to find content: &apos;/^view$/i&apos; within the element: &lt;tr&gt; but never did." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: Expected to find content: '/^view$/i' within the element: <tr> but never did.
    at Context.eval (webpack://frontend/./cypress/e2e/appointments.navigation.cy.ts:58:13)
    at withinFn (http://localhost:5173/__cypress/runner/cypress_runner.js:135871:8)
    at <unknown> (http://localhost:5173/__cypress/runner/cypress_runner.js:135952:16)
    at __WEBPACK_DEFAULT_EXPORT__ (http://localhost:5173/__cypress/runner/cypress_runner.js:133787:10)
    at Context.within (http://localhost:5173/__cypress/runner/cypress_runner.js:135938:67)
    at wrapped (http://localhost:5173/__cypress/runner/cypress_runner.js:141596:19)]]></failure>
    </testcase>
  </testsuite>
</testsuites>